spring.application.name=AlbumFigurinhaPRJ
spring.datasource.url=jdbc:sqlite:album.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true